### PR TITLE
 SG--001 feature:complete naming convention test-sg

### PR DESCRIPTION
**Pull request by sgurralaR**

### CODE REVIEW

**Comment by sgurralaR** [comment]
001 feature:complete naming convention test-sg

**Review by ejaegonzales — APPROVED** [review]
All good

**Review by sgurralaR — COMMENTED** [review]
review comments addressed

**Review by sgurralaR — COMMENTED** [review]
Please review

**Review by ejaegonzales — APPROVED** [review]
All good

**Pull request merged**
